import { CityLanguage, CountryCode, Subject, SubjectContext, SpeakerContribution } from '../types.js';
import { geocodeLocation } from './geocode.js';
import { getSubjectContextWithClaude } from './claudeSearch.js';
import { getLanguageConfig } from './language.js';
import { ResultWithUsage, NO_USAGE_STATS, type UsageStats } from './ai.js';

/**
 * Input shape for subject enrichment, compatible with both ExtractedSubject and SubjectInProgress
 */
export interface EnrichmentInput {
    name: string;
    description: string;
    locationText: string | null;
    topicImportance: 'doNotNotify' | 'normal' | 'high';
    proximityImportance: 'none' | 'near' | 'wide';
    topicLabel: string | null;
    agendaItemIndex: number | "BEFORE_AGENDA" | "OUT_OF_AGENDA";
    introducedByPersonId: string | null;
    speakerContributions: SpeakerContribution[];
    withdrawn?: boolean;
    discussedIn: string | null;
}

/**
 * Configuration for enrichment process
 */
export interface EnrichmentConfig {
    cityName: string;
    cityLanguage?: CityLanguage;
    /** ISO 3166-1 alpha-2 country of the city; geocoding is restricted to it. */
    country?: CountryCode;
    administrativeBodyName?: string;
    date: string;
}

/**
 * Shared utility for enriching subject data with geocoding and web context.
 * Used by both summarize.ts and processAgenda.ts to eliminate code duplication.
 *
 * @param input - Subject data to enrich
 * @param id - Subject ID (generated by caller based on their strategy)
 * @param config - Configuration including city name, body name, and date
 * @returns Complete Subject object with enriched data and LLM usage stats
 */
export async function enrichSubjectData(
    input: EnrichmentInput,
    id: string,
    config: EnrichmentConfig
): Promise<ResultWithUsage<Subject>> {
    // Step 1: Geocode location if provided
    let location: Subject['location'] = null;
    if (input.locationText) {
        // geocodeLocation never throws — it logs and returns null — so this
        // needs no try/catch. A null here just means the subject has no pin.
        const locationLatLng = await geocodeLocation(input.locationText + ", " + config.cityName, config.country);
        if (locationLatLng) {
            location = {
                text: input.locationText,
                type: "point" as const,
                coordinates: [[locationLatLng.lat, locationLatLng.lng]]
            };
        }
    }

    // Step 2: Fetch web context using Claude API with web search
    let context: SubjectContext;
    let usageStats: UsageStats = NO_USAGE_STATS;
    try {
        const contextResult = await getSubjectContextWithClaude({
            subjectName: input.name,
            subjectDescription: input.description,
            cityName: config.cityName,
            cityLanguage: config.cityLanguage,
            administrativeBodyName: config.administrativeBodyName || getLanguageConfig(config.cityLanguage).defaultAdministrativeBodyName,
            date: config.date
        });
        context = contextResult.result;
        usageStats = { usage: contextResult.usage, resolvedModel: contextResult.resolvedModel, batchMode: contextResult.batchMode };
    } catch (error) {
        console.error("Error fetching subject context:", error);
        context = { text: "", citationUrls: [] };
    }

    // Step 3: Construct complete Subject object
    return {
        result: {
            id,
            name: input.name,
            description: input.description,
            agendaItemIndex: input.agendaItemIndex,
            introducedByPersonId: input.introducedByPersonId,
            speakerContributions: input.speakerContributions,
            topicImportance: input.topicImportance,
            proximityImportance: input.proximityImportance,
            location,
            topicLabel: input.topicLabel,
            context,
            ...(input.withdrawn ? { withdrawn: true } : {}),
            discussedIn: input.discussedIn
        },
        ...usageStats
    };
}
