import { Subject, SubjectContext } from '../types.js';
import { geocodeLocation } from './geocode.js';
import { getSubjectContextWithClaude } from './claudeSearch.js';
import { ResultWithUsage, NO_USAGE } from './ai.js';
import Anthropic from '@anthropic-ai/sdk';

/**
 * Input shape for subject enrichment, compatible with both ExtractedSubject and SubjectInProgress
 */
export interface EnrichmentInput {
    name: string;
    description: string;
    locationText: string | null;
    topicImportance: 'doNotNotify' | 'normal' | 'high';
    proximityImportance: 'none' | 'near' | 'wide';
    topicLabel: string | null;
    agendaItemIndex: number | "BEFORE_AGENDA" | "OUT_OF_AGENDA";
    introducedByPersonId: string | null;
    speakerContributions: { speakerId: string; text: string; }[];
    discussedIn: string | null;
}

/**
 * Configuration for enrichment process
 */
export interface EnrichmentConfig {
    cityName: string;
    administrativeBodyName?: string;
    date: string;
}

/**
 * Shared utility for enriching subject data with geocoding and web context.
 * Used by both summarize.ts and processAgenda.ts to eliminate code duplication.
 *
 * @param input - Subject data to enrich
 * @param id - Subject ID (generated by caller based on their strategy)
 * @param config - Configuration including city name, body name, and date
 * @returns Complete Subject object with enriched data and LLM usage stats
 */
export async function enrichSubjectData(
    input: EnrichmentInput,
    id: string,
    config: EnrichmentConfig
): Promise<ResultWithUsage<Subject>> {
    // Step 1: Geocode location if provided
    let location: Subject['location'] = null;
    if (input.locationText) {
        try {
            const locationLatLng = await geocodeLocation(input.locationText + ", " + config.cityName);
            if (locationLatLng) {
                location = {
                    text: input.locationText,
                    type: "point" as const,
                    coordinates: [[locationLatLng.lat, locationLatLng.lng]]
                };
            }
        } catch (error) {
            console.error("Error geocoding location:", error);
            // Continue with null location on error
        }
    }

    // Step 2: Fetch web context using Claude API with web search
    let context: SubjectContext;
    let usage: Anthropic.Messages.Usage;
    try {
        const contextResult = await getSubjectContextWithClaude({
            subjectName: input.name,
            subjectDescription: input.description,
            cityName: config.cityName,
            administrativeBodyName: config.administrativeBodyName || "Δημοτικό Συμβούλιο",
            date: config.date
        });
        context = contextResult.result;
        usage = contextResult.usage;
    } catch (error) {
        console.error("Error fetching subject context:", error);
        // Return empty context on error
        context = {
            text: "",
            citationUrls: []
        };
        usage = NO_USAGE;
    }

    // Step 3: Construct complete Subject object
    return {
        result: {
            id,
            name: input.name,
            description: input.description,
            agendaItemIndex: input.agendaItemIndex,
            introducedByPersonId: input.introducedByPersonId,
            speakerContributions: input.speakerContributions,
            topicImportance: input.topicImportance,
            proximityImportance: input.proximityImportance,
            location,
            topicLabel: input.topicLabel,
            context,
            discussedIn: input.discussedIn
        },
        usage
    };
}
