services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./secrets:/app/secrets
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      TZ: "Europe/Athens"
      YTDLP_PROXY: "${YTDLP_PROXY:-}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command:
      - redis-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
    volumes:
      - ./data/redis:/data

  pgsync:
    image: toluaina1/pgsync:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SCHEMA_URL=${SCHEMA_URL}
      - PG_URL=${PG_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - ELASTICSEARCH_API_KEY_ID=${ELASTICSEARCH_API_KEY_ID}
      - REDIS_URL=redis://redis:6379/0
      - REDIS_CHECKPOINT=true
      - ELASTICSEARCH=true
      - OPENSEARCH=false
      - ELASTICSEARCH_TIMEOUT=120
      - ELASTICSEARCH_CHUNK_SIZE=10
    command: -d
    depends_on:
      - redis

x-buildkit:
  enabled: true
