/**
 * The fixture gate the differential suites open before they assert anything.
 *
 * Those suites compare against artifacts frozen from `fusion/*.py` before it
 * was deleted. The artifacts hold council speech, so they are too large and too
 * private for git and live in a local bundle instead. Every suite therefore has
 * to answer the same two questions first: is the artifact here, and is it the
 * one the committed index was pinned against?
 *
 * Answering them per suite went wrong in both directions. A bundle holding one
 * oracle instead of three still produced a green run — it just stopped checking
 * production chunking, which is the path the pipeline actually takes. And an
 * absent bundle crashed at collection rather than skipping, because
 * `describe.skip` still runs its callback and the reads sat directly inside it.
 *
 * So the gate decides once, for everyone:
 *
 *   - It names the artifacts a suite needs and reports which are missing.
 *   - A missing artifact fails the file. It does not skip it. `npm test`
 *     excludes these suites outright, so the only command that runs them is the
 *     one cited as proof the port is correct, and that one may not pass by
 *     running nothing. `FUSION_FIXTURES=optional` opts out, out loud.
 *   - Loading happens through `read`, which suites call from `beforeAll` so a
 *     skipped suite never touches the filesystem.
 *   - `verifyAgainstIndex` checks the artifact's sha256 against the index in
 *     `tests/fusion/`, so an artifact regenerated by anything other than the
 *     archived Python is caught before it is compared against.
 */
import { createHash } from "crypto";
import fs from "fs";
import os from "os";
import path from "path";

/** Where the frozen artifacts live. Overridable so the gate itself is testable. */
export const BUNDLE =
    process.env.FUSION_FIXTURES_DIR ?? path.join(os.homedir(), ".cache/oc-public/chooser-2026-08-25");

/** The committed indexes, which are in git even though the artifacts are not. */
const INDEX_DIR = path.resolve(__dirname, "../../../../tests/fusion");

/**
 * The oracle matrix the migration was accepted against: one dump per arm and
 * chunking mode that was ever compared. It is spelled out rather than globbed
 * because globbing is what let a bundle with fewer oracles pass — the suite
 * checked whatever it found and reported success for finding it.
 */
export const ORACLES = [
    { label: "rules_off", file: "oracle_rules_off_391.json", index: "ORACLE_rules_off.json" },
    {
        label: "rules_off_production",
        file: "oracle_rules_off_production_391.json",
        index: "ORACLE_rules_off_production.json",
    },
    {
        label: "rules_on_production",
        file: "oracle_rules_on_production_391.json",
        index: "ORACLE_rules_on_production.json",
    },
] as const;

/** Windows in the benchmark corpus. Every oracle must cover all of them. */
export const CORPUS_WINDOWS = 391;

/** The hypotheses every suite feeds the engine, and the index that pins them. */
export const INPUTS_FILE = "fixture_inputs_391.json";
const INPUTS_INDEX = "FIXTURE_INPUTS.json";

export interface FixtureWindow {
    id: string;
    ref: string | string[];
    hyps: string[][];
}

/**
 * True when a missing artifact is a failure rather than a skip, which is the
 * default. Fail closed: opting out has to be typed, so it cannot happen by a
 * bundle quietly going missing on someone's machine.
 */
export function fixturesRequired(): boolean {
    return process.env.FUSION_FIXTURES !== "optional";
}

export function bundleFile(name: string): string {
    return path.join(BUNDLE, name);
}

export interface Gate {
    /** Every named artifact is present. */
    readonly ready: boolean;
    /** Those that are not, for the skip reason and the failure message alike. */
    readonly missing: readonly string[];
}

/**
 * Open the gate for a suite that needs `names`.
 *
 * Under `FUSION_FIXTURES=required` this throws at module scope, which vitest
 * reports as a failed file. That is the point: the command cited as proof of
 * migration correctness must not be able to prove it by running nothing.
 */
export function gateFor(names: readonly string[]): Gate {
    const missing = names.filter((n) => !fs.existsSync(bundleFile(n)));
    if (missing.length && fixturesRequired()) {
        throw new Error(
            `fixture bundle incomplete: ${missing.join(", ")} not under ${BUNDLE}. ` +
                `These suites are the acceptance evidence for the port, so a missing ` +
                `artifact fails rather than skips; run with FUSION_FIXTURES=optional to ` +
                `skip anyway. See docs/fusion-python-archive.md for what produced these ` +
                `and tests/fusion/README.md for where to get them.`,
        );
    }
    return { ready: missing.length === 0, missing };
}

/** Read an artifact out of the bundle. Call from `beforeAll`, never at suite scope. */
export function read<T>(name: string): T {
    return JSON.parse(fs.readFileSync(bundleFile(name), "utf8")) as T;
}

/** Read a committed index. These are in git, so no gate is needed. */
export function readIndex<T = Record<string, unknown>>(name: string): T {
    return JSON.parse(fs.readFileSync(path.join(INDEX_DIR, name), "utf8")) as T;
}

function sha256OfFile(file: string): string {
    return createHash("sha256").update(fs.readFileSync(file)).digest("hex");
}

interface ArtifactIndex {
    file: string;
    sha256: string;
    python: string;
    unicodedata: string;
}

/**
 * Check an artifact against the index committed beside it.
 *
 * The sha256 is the part that matters: it is what distinguishes the dump the
 * archived CPython 3.14.6 produced from one regenerated by something else. The
 * interpreter and Unicode versions are carried too, because they are the two
 * things known to change the numbers — `sum()` became compensated in 3.12, and
 * `\w` follows the Unicode version — and reporting them makes a mismatch
 * readable instead of appearing as an unexplained hash difference.
 */
export function verifyAgainstIndex(artifact: string, indexName: string): ArtifactIndex {
    const index = readIndex<ArtifactIndex>(indexName);
    if (index.file !== artifact) {
        throw new Error(`${indexName} indexes ${index.file}, not ${artifact}`);
    }
    const got = sha256OfFile(bundleFile(artifact));
    if (got !== index.sha256) {
        throw new Error(
            `${artifact} does not match ${indexName}: expected sha256 ${index.sha256}, got ${got}. ` +
                `The artifact in the bundle was not the one this repo was pinned against. ` +
                `Do not update the index to make this pass — regenerate from the ` +
                `python-engine-last-known-good tag (CPython ${index.python}, Unicode ${index.unicodedata}).`,
        );
    }
    return index;
}

/**
 * The verified corpus inputs, loaded once for whoever asks.
 *
 * Both the fusion and conformance suites feed the engine this file, and both
 * used to read it unchecked — the only sha256 for it lived in the bundle's own
 * manifest, which is a bundle vouching for itself. `FIXTURE_INPUTS.json` puts
 * that hash in git instead.
 */
export function loadInputs(): FixtureWindow[] {
    verifyAgainstIndex(INPUTS_FILE, INPUTS_INDEX);
    const { windows } = read<{ windows: FixtureWindow[] }>(INPUTS_FILE);
    if (windows.length !== CORPUS_WINDOWS) {
        throw new Error(`${INPUTS_FILE} holds ${windows.length} windows, expected ${CORPUS_WINDOWS}`);
    }
    return windows;
}
